FROM python:3.12.8-slim-bookworm

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install jupyter==1.1.1 pandas==3.0.1

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser", "--NotebookApp.token=''"]